### ISSUE TITLE
accepts_nested_attributes_for not work

### ISSUE THREAD

**Issue by bastengao** [jasl-lab/duck_record#1]
```ruby
require 'duck_record'

class Person < DuckRecord::Base
  attribute :name, :string
  attribute :age, :integer

  validates :name, presence: true
end

class Comment < DuckRecord::Base
  attribute :content, :string

  validates :content, presence: true
end

class Book < DuckRecord::Base
  embeds_one :author, class_name: 'Person', validate: true
  accepts_nested_attributes_for :author

  embeds_many :comments, validate: true
  accepts_nested_attributes_for :comments

  attribute :title,     :string
  attribute :tags,      :string,   array:   true
  attribute :price,     :decimal,  default: 0
  attribute :meta,      :json,     default: {}
  attribute :bought_at, :datetime, default: -> { Time.new } 

  validates :title, presence: true
end

book = Book.new(title: "hello", author_attributes: { name: "h", age: 10 })
puts book.attributes

# Output missing author:
# {"title"=>"hello", "tags"=>nil, "price"=>0.0, "meta"=>{}, "bought_at"=>2018-04-19 07:28:01 UTC}
```

**Comment by jasl** [comment]
That's design, it follows AR's behavior.

```
book.author
# <Person:0x007ff6245bf528 name: "h", age: 10>
```

Actually the `author` is set correctly, if you want to get serialized hash with nested objects:

- I recommend using `serializable_hash` method, see <http://api.rubyonrails.org/classes/ActiveModel/Serialization.html#method-i-serializable_hash>
- There's an argument called `include` in `serializable_hash` (see doc above) can specify which relationships you want to serialize

So, If you want dump object with all nested relationships, you need to do like:

```
book.serializable_hash include: (Book._reflections.select { |_, v| v.is_a? DuckRecord::Reflection::EmbedsAssociationReflection }.keys)

# {"title"=>"hello",
#  "tags"=>nil,
#  "price"=>0.0,
#  "meta"=>{},
#  "bought_at"=>2018-04-19 07:31:55 UTC,
#  "author"=>{"name"=>"h", "age"=>10},
#  "comments"=>[]}
```

You can wrap this like <https://github.com/rails-engine/form_core/blob/master/test/dummy/app/lib/field_options.rb#L13-L16>

I'm not include this just because making the same behavior is the first of my concerns.

**Comment by jasl** [comment]
BTW, `Book._reflections.select { |_, v| v.is_a? DuckRecord::Reflection::EmbedsAssociationReflection }` means I just wanna dump objects which is embeds relationship, since DuckRecord also support relationship with real models

**Comment by bastengao** [comment]
Got it, thanks.
